spring.profiles.active=crud,no-auth
spring.config.import=configtree:/app/config/

dynamic.properties.path=

server.port=8080
server.servlet.context-path=/resource-catalogue

logging.level.root=INFO

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.open-in-view=false
spring.main.allow-bean-definition-overriding=true

spring.data.redis.host=redis
spring.data.redis.password=${_REDIS_PASSWORD}
spring.data.redis.database=${_REDIS_DATABASE}
spring.data.redis.port=6379

fqdn=${_FQDN}

aai.baseUrl=${_AUTH_SERVER_URL}
spring.security.oauth2.client.registration.google.client-id=${fqdn}
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://${fqdn}:8080/resource-catalogue/openid_connect_login
spring.security.oauth2.client.registration.eosc.client-name=${fqdn}
spring.security.oauth2.client.registration.eosc.client-id=${_OAUTH2_EOSC_CLIENT_ID}
spring.security.oauth2.client.registration.eosc.client-secret=${_OAUTH2_EOSC_CLIENT_SECRET}
spring.security.oauth2.client.registration.eosc.scope=openid,email,profile
spring.security.oauth2.client.registration.eosc.redirect-uri=http://${fqdn}:8080/resource-catalogue/openid_connect_login
spring.security.oauth2.client.provider.eosc.issuer-uri=${aai.baseUrl}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${aai.baseUrl}

springdoc.api-docs.path=/api-docs

springdoc.group-configs[0].group=1
springdoc.group-configs[0].display-name=Resource Catalogue
springdoc.group-configs[0].packages-to-scan=gr.uoa.di.madgik.resourcecatalogue
springdoc.group-configs[1].group=2
springdoc.group-configs[1].display-name=Dynamic Catalogue
springdoc.group-configs[1].packages-to-scan=gr.uoa.di.madgik.catalogue
springdoc.group-configs[2].group=3
springdoc.group-configs[2].display-name=Registry
springdoc.group-configs[2].packages-to-scan=gr.uoa.di.madgik.registry

springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.syntaxHighlight.activated=false
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

spring.jackson.default-property-inclusion=NON_NULL

registry.host=http://${fqdn}:${server.port}${server.servlet.context-path}

registry.datasource.configuration.maximum-pool-size=6
registry.datasource.driver-class-name=org.postgresql.Driver
registry.datasource.username=catalogue
registry.datasource.password=${_CATALOGUE_DATABASE_PASSWORD}
registry.datasource.url=jdbc:postgresql://postgres:5432/${_CATALOGUE_DATABASE_NAME}

registry.jpa.properties.hibernate.allow_update_outside_transaction=true
registry.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
registry.jpa.properties.hibernate.enable_lazy_load_no_trans=true
registry.jpa.properties.hibernate.format_sql=false
registry.jpa.properties.hibernate.hbm2ddl.auto=validate
registry.jpa.properties.hibernate.show_sql=false

jdbc.hikari.connectionTimeout=30000
jdbc.hikari.idleTimeout=120000
jdbc.hikari.maximumPoolSize=6
jdbc.hikari.maxLifetime=1800000
jdbc.hikari.minimumIdle=3

spring.flyway.enabled=false

registry.elasticsearch.uris=
registry.elasticsearch.username=
registry.elasticsearch.password=

registry.jms.host=
registry.jms.prefix=
registry.jms.username=
registry.jms.password=

catalogue.id=services-catalogue
catalogue.name=services-catalogue
catalogue.homepage=
catalogue.version=@project.version@

catalogue.admins=devops-eosc@athenarc.gr
catalogue.admins=nikleonidakis@gmail.com
catalogue.onboarding-team=
catalogue.login-redirect=http://localhost:3000
catalogue.logout-redirect=http://localhost:3000

catalogue.resources.configuration-template.id-prefix=con
catalogue.resources.configuration-template-instance.id-prefix=cti
catalogue.resources.datasource.id-prefix=dat
catalogue.resources.helpdesk.id-prefix=hel

catalogue.resources.interoperability-record.id-prefix=${_IFG_PID_PREFIX}
catalogue.resources.interoperability-record.pid-issuer.url=${_IFG_PID_SERVER_URL}
catalogue.resources.interoperability-record.pid-issuer.user=${_IFG_PID_USER}
catalogue.resources.interoperability-record.pid-issuer.user-index=${_IFG_PID_USER_INDEX}
catalogue.resources.interoperability-record.pid-issuer.auth.client-key=/secrets/pid/clients/ifg/client.key
catalogue.resources.interoperability-record.pid-issuer.auth.client-cert=/secrets/pid/clients/ifg/client.crt

catalogue.resources.monitoring.id-prefix=mon

catalogue.resources.provider.id-prefix=${_PROVIDERS_PID_PREFIX}
catalogue.resources.provider.pid-issuer.url=${_PROVIDERS_PID_SERVER_URL}
catalogue.resources.provider.pid-issuer.user=${_PROVIDERS_PID_USER}
catalogue.resources.provider.pid-issuer.user-index=${_PROVIDERS_PID_USER_INDEX}
catalogue.resources.provider.pid-issuer.auth.client-key=/secrets/pid/clients/providers/client.key
catalogue.resources.provider.pid-issuer.auth.client-cert=/secrets/pid/clients/providers/client.crt

catalogue.resources.resource-interoperability-record.id-prefix=rir

catalogue.resources.service.id-prefix=${_SERVICES_PID_PREFIX}
catalogue.resources.service.pid-issuer.url=${_SERVICES_PID_SERVER_URL}
catalogue.resources.service.pid-issuer.user=${_SERVICES_PID_USER}
catalogue.resources.service.pid-issuer.user-index=${_SERVICES_PID_USER_INDEX}
catalogue.resources.service.pid-issuer.auth.client-key=/secrets/pid/clients/services/client.key
catalogue.resources.service.pid-issuer.auth.client-cert=/secrets/pid/clients/services/client.crt

catalogue.resources.tool.id-prefix=${_TOOLS_PID_PREFIX}
catalogue.resources.tool.pid-issuer.url=${_TOOLS_PID_SERVER_URL}
catalogue.resources.tool.pid-issuer.user=${_TOOLS_PID_USER}
catalogue.resources.tool.pid-issuer.user-index=${_TOOLS_PID_USER_INDEX}
catalogue.resources.tool.pid-issuer.auth.client-key=/secrets/pid/clients/tools/client.key
catalogue.resources.tool.pid-issuer.auth.client-cert=/secrets/pid/clients/tools/client.crt

catalogue.resources.training-resource.id-prefix=${_TRAINING_PID_PREFIX}
catalogue.resources.training-resource.pid-issuer.url=${_TRAINING_PID_SERVER_URL}
catalogue.resources.training-resource.pid-issuer.user=${_TRAINING_PID_USER}
catalogue.resources.training-resource.pid-issuer.user-index=${_TRAINING_PID_USER_INDEX}
catalogue.resources.training-resource.pid-issuer.auth.client-key=/secrets/pid/clients/training/client.key
catalogue.resources.training-resource.pid-issuer.auth.client-cert=/secrets/pid/clients/training/client.crt

catalogue.resources.vocabulary-curation.id-prefix=cur

catalogue.emails.enabled=false
catalogue.emails.admin-notifications=false
catalogue.emails.provider-notifications=false
catalogue.emails.registration-emails.to=
catalogue.emails.helpdesk-emails.to=
catalogue.emails.helpdesk-emails.cc=
catalogue.emails.monitoring-emails.to=
catalogue.emails.resource-consistency-notifications=false
catalogue.emails.resource-consistency-emails.to=
catalogue.emails.resource-consistency-emails.cc=

catalogue.mailer.host=
catalogue.mailer.from=
catalogue.mailer.username=
catalogue.mailer.password=
catalogue.mailer.port=
catalogue.mailer.protocol=
catalogue.mailer.auth=true
catalogue.mailer.ssl=true

matomo.authorization.header=
matomo.host=
matomo.token=
matomo.site-id=

openaire.ds.api=
openaire.ds.metrics=
openaire.ds.metrics.validated=

argo.grnet.monitoring.availability=
argo.grnet.monitoring.service.types=
argo.grnet.monitoring.status=
argo.grnet.monitoring.token=

sync.enable=false
sync.host=
sync.token.filepath=

