name: Build image
run-name: build image

on: 
  push:
    branches:
    #- 'eosc'
    tags:
    - 'v5.*'
  
permissions:
  actions: read
  checks: read
  contents: read
  packages: write
  repository-projects: read
  statuses: read
 
jobs:

  build_image: 
    runs-on:
    - self-hosted
    - x64
    - debian-12
    if: >-
      github.ref_type == 'tag'
    steps:
    - run: >-
        echo "app_version=$(echo ${{ github.ref_name }} | grep -Po '^v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV
    - run: >-
        echo "app_version=${{ env.app_version }}"
    - uses: actions/checkout@v3
    - run: >-
        echo "short_commit=$(echo ${{ github.sha }} | cut -b 1-7)" >> $GITHUB_ENV
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v3
      with:
        driver: docker
    - uses: docker/bake-action@v4
      with:
        targets: 'default'
        push: true
        set: |
          default.args.git_commit=${{ github.sha }}
          default.args.app_version=${{ env.app_version }}
          default.tags=ghcr.io/eosc-lot-1/resource-catalogue:${{ env.app_version }}
          default.tags=ghcr.io/eosc-lot-1/resource-catalogue:${{ env.short_commit }}

